### PR TITLE
:star2: (parser) Support for multiple types of default value displayed

### LINKED ISSUE #76: Eslint and vuese default properties
**Describe the bug**
The default declaration to an array property in Eslint is
`default () { return [] }`
like they describe in this link https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/require-valid-default-prop.md,
but when i use vuese my output is the below because vuese search for 
`default: []`

**Vuese output pictures**

Screenshot_2019-05-21 TraysCard - Components

### PR DESCRIPTION
**Pull request by hefeng1208**
Closes #76

### CODE REVIEW

File: packages/parser/lib/processProps.ts [hunk 1]
```diff
@@ -35,15 +35,22 @@ export function processPropValue(propValueNode: bt.Node, result: PropsResult) {
         result.typeDesc = typeDesc
       }
     }
-
+    // Processing props's default value
     otherNodes.forEach((node: any) => {
       const n = node.key.name
       if (n === 'default') {
-        if (!hasFunctionTypeDef(result.type) && bt.isFunction(node.value)) {
```
Comment (HcySunYang) [inline packages/parser/lib/processProps.ts:42]: When a prop type is function , we should not execute this function, for example:
```js
{
   propA: {
      type: Function,
      default: function () {
          // ......
      }
    }
}
```
Because the type of propA is a function, the default value should be the function itself, not the result of the function.

So this test case is incorrect: https://github.com/vue-contrib/vuese/pull/106/files#diff-769dd406bade87c948da829f10edee1dL243

**Review by HcySunYang — CHANGES_REQUESTED** [review]

File: packages/parser/lib/processProps.ts (hunk 1 above)
Comment (HcySunYang) [reply packages/parser/lib/processProps.ts:42]: Thank you very much for your great work. 🤟

**Comment by mattmink** [comment]
Somehow, this appears to have broken all of my default values. The default column now shows `-` for all props, regardless of default type.

**Comment by HcySunYang** [comment]
Can you give me a sample component? @matthewjmink

**Comment by ChristianKienle** [comment]
@HcySunYang 

Here:

```vue
<template>
  <div>
    <!-- Form header -->
    <slot name="header">
      <!-- `<th>title</th>` -->
      <th>title</th>
    </slot>
  </div>
</template>

<script>
// This is a description of the component
export default {
  name: 'MyComponent',
  props: {
    hello: {
      type: Boolean,
      default: true
    },
    // The name of the form, up to 8 characters
    name: {
      type: [String, Number],
      required: true,
      validator () {}
    }
  },
  methods: {
    // @vuese
    // Used to manually clear the form
    clear () {
      // Fire when the form is cleared
      // @arg The argument is a boolean value representing xxx
      this.$emit('onclear', true)
    }
  }
}
</script>
```
Paste the above code in vuese explorer and you should see the issue.

**Comment by mattmink** [comment]
Thanks @ChristianKienle. I had forgotten to reply.
